services:
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hassusalakala
      - POSTGRES_USER=pgvector
      - POSTGRES_DB=embeddings

volumes:
  db:
